networks:
  mongo_network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: my_mongo_express
    ports:
      - "8081:8081" # Exponer Mongo Express en el puerto 8081 en el host
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo # Nombre del servicio de MongoDB
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: "" # Nombre de usuario, si existe
      ME_CONFIG_MONGODB_ADMINPASSWORD: "" # Contraseña, si existe
    networks:
      - mongo_network
    restart: always

volumes:
  mongo_data:
